version: '3'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'tsoxos/argiridis_thesis'
    container_name: argiridis_thesis_app
    ports: 
      - "9000:80"
    networks:
      - thesis_network
    depends_on:
      - db
    restart: on-failure
  db:
    image: mariadb
    container_name: argiridis_thesis_db
    restart: always
    ports:
      - "3123:3306"
    environment:
      MYSQL_DATABASE: 'fivos_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - thesis_network
networks:
    thesis_network:
        driver: bridge
volumes:
    thesis_db:
        driver: local